import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.backgroundRoot,
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: Spacing['2xl'],
      paddingTop: Spacing['2xl'],
      paddingBottom: Spacing['2xl'],
    },
    header: {
      marginBottom: Spacing.xl,
    },
    title: {
      fontSize: 32,
      fontWeight: '700',
      color: theme.textPrimary,
      marginBottom: Spacing.sm,
      letterSpacing: -0.5,
    },
    subtitle: {
      fontSize: 15,
      color: theme.textMuted,
      lineHeight: 22,
      marginBottom: Spacing.md,
    },
    dateTimeSection: {
      marginBottom: Spacing.lg,
    },
    dateWeatherRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      flexWrap: 'wrap',
    },
    dateWeatherText: {
      fontSize: 13,
      fontWeight: '500',
    },
    writingSection: {
      marginBottom: Spacing.xl,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.sm,
    },
    sectionTitle: {
      fontSize: 17,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    dailyEntriesLink: {
      fontSize: 14,
      fontWeight: '600',
    },
    inputCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: BorderRadius['2xl'],
      borderWidth: 2,
      borderColor: theme.border,
      padding: Spacing.lg,
      minHeight: 150,
      marginTop: Spacing.sm,
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 2,
    },
    textInput: {
      flex: 1,
      fontSize: 16,
      color: theme.textPrimary,
      textAlignVertical: 'top',
      minHeight: 150,
    },
    moodSection: {
      marginTop: Spacing.lg,
      paddingTop: Spacing.md,
      borderTopWidth: 1,
      borderTopColor: theme.borderLight,
    },
    moodLabel: {
      marginBottom: Spacing.sm,
    },
    moodButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    moodButton: {
      flex: 1,
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.lg,
      borderWidth: 2,
      borderColor: theme.borderLight,
      backgroundColor: 'transparent',
      gap: Spacing.xs,
    },
    moodButtonSelected: {
      backgroundColor: 'rgba(0, 0, 0, 0.02)',
    },
    moodButtonText: {
      fontSize: 12,
    },
    mediaSection: {
      marginBottom: Spacing.xl,
    },
    mediaButtons: {
      flexDirection: 'row',
      gap: Spacing.md,
      marginTop: Spacing.lg,
    },
    mediaButton: {
      flex: 1,
      backgroundColor: '#FFFFFF',
      borderRadius: BorderRadius.lg,
      borderWidth: 2,
      borderColor: theme.border,
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing.xl,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.sm,
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      elevation: 2,
    },
    mediaButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    mediaButtonActive: {
      backgroundColor: 'rgba(123,110,246,0.15)',
      borderColor: 'rgba(123,110,246,0.3)',
    },
    mediaButtonActiveText: {
      color: theme.primary,
    },
    uploadedMediaContainer: {
      marginTop: Spacing.lg,
      gap: Spacing.sm,
    },
    imageItem: {
      width: '100%',
      height: 200,
      borderRadius: BorderRadius.lg,
      overflow: 'hidden',
      backgroundColor: 'rgba(255,255,255,0.06)',
    },
    imageItemThumbnail: {
      width: '100%',
      height: '100%',
    },
    removeButton: {
      position: 'absolute',
      top: 8,
      right: 8,
      backgroundColor: 'rgba(0,0,0,0.6)',
      borderRadius: 9999,
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
    },
    audioItem: {
      backgroundColor: 'rgba(255,255,255,0.06)',
      borderRadius: BorderRadius.lg,
      borderWidth: 1,
      borderColor: theme.borderLight,
      padding: Spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
    },
    audioIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(92,224,216,0.12)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    audioInfo: {
      flex: 1,
    },
    audioDuration: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    audioStatus: {
      fontSize: 12,
      color: theme.textMuted,
      marginTop: 2,
    },
    submitButton: {
      backgroundColor: '#2C3E50',
      borderRadius: 9999,
      borderWidth: 1,
      borderColor: '#2C3E50',
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing['2xl'],
      alignItems: 'center',
      flex: 1,
      shadowColor: '#2C3E50',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 16,
      elevation: 5,
    },
    submitButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: '#FFFFFF',
      letterSpacing: 0.3,
    },
    buttonGroup: {
      flexDirection: 'row',
      gap: Spacing.md,
    },
    chatButton: {
      backgroundColor: theme.primary,
      borderRadius: 9999,
      borderWidth: 1,
      borderColor: theme.primary,
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing.xl,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: Spacing.xs,
      flex: 1,
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 20,
      elevation: 8,
    },
    buttonText: {
      fontSize: 16,
      fontWeight: '700',
      letterSpacing: 0.5,
    },
    recordingIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    recordingDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.error,
    },
    recordingTime: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textPrimary,
    },
  });
};
