import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.backgroundRoot,
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.xl,
      paddingBottom: Spacing.lg,
    },
    header: {
      marginBottom: Spacing.md,
    },
    title: {
      fontSize: 36,
      fontWeight: '400',
      color: theme.textPrimary,
      marginBottom: 4,
      letterSpacing: -0.5,
    },
    subtitle: {
      fontSize: 15,
      color: theme.textSecondary,
      lineHeight: 22,
      marginBottom: Spacing.sm,
    },
    dateTimeSection: {
      marginBottom: Spacing.md,
    },
    dateWeatherRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flexWrap: 'wrap',
    },
    dateWeatherText: {
      fontSize: 13,
      fontWeight: '500',
    },
    writingSection: {
      marginBottom: Spacing.md,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.xs,
    },
    sectionTitle: {
      fontSize: 12,
      fontWeight: '600',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      opacity: 0.6,
      color: theme.textPrimary,
    },
    dailyEntriesLink: {
      fontSize: 14,
      fontWeight: '600',
    },
    inputCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: BorderRadius.md,
      borderWidth: 1,
      borderColor: theme.border,
      padding: Spacing.md,
      minHeight: 150,
      marginTop: Spacing.xs,
    },
    textInput: {
      flex: 1,
      fontSize: 15,
      color: theme.textPrimary,
      textAlignVertical: 'top',
      minHeight: 150,
      lineHeight: 22,
    },
    moodSection: {
      marginTop: Spacing.sm,
      paddingTop: Spacing.sm,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    moodLabel: {
      marginBottom: Spacing.xs,
      fontSize: 12,
      fontWeight: '600',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      opacity: 0.6,
    },
    moodButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: Spacing.xs,
    },
    moodButton: {
      flex: 1,
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      borderRadius: BorderRadius.sm,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: 'transparent',
      gap: 6,
    },
    moodButtonSelected: {
      backgroundColor: 'rgba(255, 158, 125, 0.08)',
    },
    moodButtonText: {
      fontSize: 12,
    },
    mediaSection: {
      marginBottom: Spacing.md,
    },
    mediaButtons: {
      flexDirection: 'row',
      gap: Spacing.sm,
      marginTop: Spacing.sm,
    },
    mediaButton: {
      flex: 1,
      backgroundColor: '#FFFFFF',
      borderRadius: BorderRadius.sm,
      borderWidth: 1,
      borderColor: theme.border,
      paddingVertical: 16,
      paddingHorizontal: Spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    mediaButtonText: {
      fontSize: 14,
      fontWeight: '500',
      color: theme.textPrimary,
    },
    mediaButtonActive: {
      backgroundColor: 'rgba(255, 158, 125, 0.1)',
      borderColor: theme.primary,
    },
    mediaButtonActiveText: {
      color: theme.primary,
    },
    uploadedMediaContainer: {
      marginTop: Spacing.sm,
      gap: Spacing.xs,
    },
    imageItem: {
      width: '100%',
      height: 200,
      borderRadius: BorderRadius.sm,
      overflow: 'hidden',
      backgroundColor: theme.backgroundTertiary,
    },
    imageItemThumbnail: {
      width: '100%',
      height: '100%',
    },
    removeButton: {
      position: 'absolute',
      top: 8,
      right: 8,
      backgroundColor: 'rgba(26, 26, 26, 0.6)',
      borderRadius: 999,
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
    },
    audioItem: {
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.sm,
      borderWidth: 1,
      borderColor: theme.border,
      padding: Spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    audioIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(197, 222, 167, 0.2)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    audioInfo: {
      flex: 1,
    },
    audioDuration: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    audioStatus: {
      fontSize: 12,
      color: theme.textMuted,
      marginTop: 2,
    },
    submitButton: {
      backgroundColor: theme.cardDark,
      borderRadius: 999,
      paddingVertical: 16,
      paddingHorizontal: Spacing.md,
      alignItems: 'center',
      flex: 1,
    },
    submitButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#F7F5F1',
    },
    buttonGroup: {
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    chatButton: {
      backgroundColor: theme.primary,
      borderRadius: 999,
      paddingVertical: 16,
      paddingHorizontal: Spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
      flex: 1,
    },
    buttonText: {
      fontSize: 14,
      fontWeight: '600',
    },
    recordingIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    recordingDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.error,
    },
    recordingTime: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.textPrimary,
    },
  });
};
